export const dataHeight = {
  datasets: [
    {
      label: "Rất thấp",
      data: [
        { x: 40, y: 1 },
        { x: 50, y: 1 },
        { x: 60, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Thấp",
      data: [
        { x: 50, y: 0 },
        { x: 60, y: 1 },
        { x: 80, y: 1 },
        { x: 90, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Bình thường",
      data: [
        { x: 80, y: 0 },
        { x: 90, y: 1 },
        { x: 110, y: 1 },
        { x: 120, y: 0 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Cao",
      data: [
        { x: 110, y: 0 },
        { x: 120, y: 1 },
        { x: 140, y: 1 },
        { x: 150, y: 0 },
      ],
      borderColor: "orange",
      borderWidth: 2,
      backgroundColor: "orange",
      pointBackgroundColor: "orange",
      pointBorderColor: "orange",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Rất cao",
      data: [
        { x: 140, y: 0 },
        { x: 150, y: 1 },
        { x: 160, y: 1 },
      ],
      borderColor: "purple",
      borderWidth: 2,
      backgroundColor: "purple",
      pointBackgroundColor: "purple",
      pointBorderColor: "purple",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};
export const dataWeight = {
  datasets: [
    {
      label: "Rất nhẹ",
      data: [
        { x: 0, y: 1 },
        { x: 8, y: 1 },
        { x: 10, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Nhẹ",
      data: [
        { x: 8, y: 0 },
        { x: 10, y: 1 },
        { x: 18, y: 1 },
        { x: 20, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },

    {
      label: "Bình thường",
      data: [
        { x: 18, y: 0 },
        { x: 20, y: 1 },
        { x: 28, y: 1 },
        { x: 30, y: 0 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Nặng",
      data: [
        { x: 28, y: 0 },
        { x: 30, y: 1 },
        { x: 38, y: 1 },
        { x: 40, y: 0 },
      ],
      borderColor: "orange",
      borderWidth: 2,
      backgroundColor: "orange",
      pointBackgroundColor: "orange",
      pointBorderColor: "orange",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Rất nặng",
      data: [
        { x: 38, y: 0 },
        { x: 40, y: 1 },
        { x: 45, y: 1 },
      ],
      borderColor: "purple",
      borderWidth: 2,
      backgroundColor: "purple",
      pointBackgroundColor: "purple",
      pointBorderColor: "purple",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};
export const dataSleepingTime = {
  datasets: [
    {
      label: "Rất ít",
      data: [
        { x: 6, y: 1 },
        { x: 7, y: 1 },
        { x: 8, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Ít",
      data: [
        { x: 7, y: 0 },
        { x: 8, y: 1 },
        { x: 9, y: 1 },
        { x: 10, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },

    {
      label: "Bình thường",
      data: [
        { x: 9, y: 0 },
        { x: 10, y: 1 },
        { x: 11, y: 1 },
        { x: 12, y: 0 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Nhiều",
      data: [
        { x: 11, y: 0 },
        { x: 12, y: 1 },
        { x: 13, y: 1 },
        { x: 14, y: 0 },
      ],
      borderColor: "orange",
      borderWidth: 2,
      backgroundColor: "orange",
      pointBackgroundColor: "orange",
      pointBorderColor: "orange",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Rất nhiều",
      data: [
        { x: 13, y: 0 },
        { x: 14, y: 1 },
        { x: 16, y: 1 },
      ],
      borderColor: "purple",
      borderWidth: 2,
      backgroundColor: "purple",
      pointBackgroundColor: "purple",
      pointBorderColor: "purple",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};
export const dataDI = {
  datasets: [
    {
      label: "Kém",
      data: [
        { x: 0, y: 0 },
        { x: 25, y: 1 },
        { x: 50, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Bình thường",
      data: [
        { x: 25, y: 0 },
        { x: 50, y: 1 },
        { x: 75, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Tốt",
      data: [
        { x: 50, y: 0 },
        { x: 75, y: 1 },
        { x: 100, y: 0 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    }
  ],
};

export const dataDI2 = {
  datasets: [
    {
      label: "Kém",
      data: [
        { x: 0, y: 0 },
        { x: 25, y: 1 },
        { x: 50, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Bình thường",
      data: [
        { x: 25, y: 0 },
        { x: 50, y: 1 },
        { x: 75, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Tốt",
      data: [
        {x: 50, y: 0 },
        { x: 75, y: 1 },
        { x: 100, y: 0 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};